Fix type import from cucumber-expressions
ParameterType is now properly exported so no need to directly reference it.

Without this change tsc files for me with the following error:
```
node_modules/@cucumber/cucumber/lib/support_code_library_builder/sourced_parameter_type_registry.d.ts:2:27 - error TS2307: Cannot find module '@cucumber/cucumber-expressions/dist/cjs/src/ParameterType' or its corresponding type declarations.

2 import ParameterType from '@cucumber/cucumber-expressions/dist/cjs/src/ParameterType';
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error in node_modules/@cucumber/cucumber/lib/support_code_library_builder/sourced_parameter_type_registry.d.ts:2
```